spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:petshopdb
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

spring.security.user.name=OleksandraSkoryk
spring.security.user.password=123456
spring.security.user.roles=ADMIN

server.port=8080


